### ISSUE TITLE
Please add support for Ubuntu 20.04

### ISSUE THREAD

**Issue by dhoppe** [puppetlabs/litmusimage#21]
## Use Case
Litmus should be able to test Puppet modules against Ubuntu 20.04.

## Describe the Solution You Would Like
I would like to have a Docker image for Ubuntu 20.04.

## Describe Alternatives You've Considered
I am not sure if ```apt_sysvinit-utils_dockerfile``` could be used. In this case a pull request would only contain two additional lines, regarding the GitHub actions. 

## Additional Context
http://releases.ubuntu.com/focal/

**Comment by DavidS** [comment]
puppet_agent install support was just merged in https://tickets.puppetlabs.com/browse/MODULES-10651

**Comment by DavidS** [comment]
assuming Ubuntu 20.04 is not deviating from current global defaults, `apt_systemd_dockerfile` is gonna be more appropriate.

**Comment by dhoppe** [comment]
I know, but I have no clue why Ubuntu 16.04 uses ```apt_systemd_dockerfile``` and Ubuntu 18.04 ```apt_sysvinit-utils_dockerfile```. Debian 10 uses ```apt_sysvinit-utils_dockerfile``` too. 

* https://github.com/puppetlabs/litmusimage/blob/master/.github/workflows/build_dockerfiles.yml#L13-L14

**Comment by DavidS** [comment]
This is now also being tracked as IAC-771

**Comment by DavidS** [comment]
d'oh, yeah, looking into it the `apt_sysvinit-utils_dockerfile` is the correct one, but a bit of a misnomer.

**Comment by DavidS** [comment]
This was addressed in #23
